[package]
name = "teldrassil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.6", features = ["headers"] }
async-graphql = { version = "5.0", features = ["uuid", "chrono"] }
async-graphql-axum = "5.0"